name: Run Python tests1

on:
  push:
    branches:
      - main
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Cambia la versión si usas otra

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Si tienes requirements.txt, descomenta la siguiente línea:
          # pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s test
